export const protocolTypes = {
    GET_PROTOCOLS: "GET_PROTOCOLS",
    UPDATE_PROTOCOLS: "UPDATE_PROTOCOLS",
    SET_PROTOCOLS: "SET_PROTOCOLS",
    POST_PROTOCOL: "POST_PROTOCOL",
    PUT_PROTOCOL: "PUT_PROTOCOL",
}